# Generated by Django 3.0.2 on 2006-08-30 21:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('examples', '0004_student'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='year_in_school',
            field=models.CharField(choices=[('FR', 'Freshman'), ('SO', 'Sophomore'), ('JR', 'Junior'), ('SR', 'Senior'), ('GR', 'Graduate')], default='FR', max_length=2),
        ),
    ]
