# Generated by Django 3.0.2 on 2006-08-27 22:21

from django.db import migrations, models
import examples.validators


class Migration(migrations.Migration):

    dependencies = [
        ('examples', '0005_student_year_in_school'),
    ]

    operations = [
        migrations.CreateModel(
            name='Example0',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('even_field', models.IntegerField(validators=[examples.validators.validate_even])),
            ],
        ),
    ]
