# Generated by Django 3.0.2 on 2006-08-28 05:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reporter',
            name='full_name',
        ),
        migrations.AddField(
            model_name='reporter',
            name='first_name',
            field=models.CharField(default=None, max_length=70),
        ),
        migrations.AddField(
            model_name='reporter',
            name='last_name',
            field=models.CharField(default=None, max_length=70),
        ),
        migrations.AddField(
            model_name='reporter',
            name='sirname',
            field=models.CharField(default=None, max_length=70),
        ),
    ]
