# Generated by Django 3.0.2 on 2006-08-28 03:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('generic0', '0003_auto_20060828_0041'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='author',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='book',
            options={'ordering': ['title', '-publication_date', 'publisher']},
        ),
    ]
