# Generated by Django 4.0 on 2021-12-22 09:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('generic0', '0004_auto_20060828_0608'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='publisher',
            options={},
        ),
    ]
