# Generated by Django 3.0.2 on 2006-08-30 21:05

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('myblog', '0004_auto_20060828_0152'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='date_published',
            field=models.DateTimeField(default=datetime.datetime(2006, 8, 30, 21, 5, 35, 84960, tzinfo=utc)),
        ),
    ]
