# Generated by Django 3.0.2 on 2006-08-31 04:58

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('myblog', '0005_auto_20060831_0005'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='date_published',
            field=models.DateTimeField(default=datetime.datetime(2006, 8, 31, 4, 58, 15, 866210, tzinfo=utc)),
        ),
    ]
