# Generated by Django 3.0.2 on 2006-09-01 03:17

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('myblog', '0006_auto_20060831_0758'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='date_published',
            field=models.DateTimeField(default=datetime.datetime(2006, 9, 1, 3, 15, 59, 582031, tzinfo=utc)),
        ),
    ]
