# Generated by Django 3.0.2 on 2006-09-03 00:04

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('myblog', '0007_auto_20060901_0617'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='date_published',
            field=models.DateTimeField(default=datetime.datetime(2006, 9, 3, 0, 4, 54, 454101, tzinfo=utc)),
        ),
    ]
