# Generated by Django 3.0.2 on 2006-09-03 00:10

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('myblog', '0008_auto_20060903_0304'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='date_published',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
