# Generated by Django 3.0.2 on 2006-08-27 21:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_hint'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hint',
            name='hint_text',
            field=models.TextField(max_length=200),
        ),
    ]
