# Generated by Django 3.0.2 on 2006-08-27 21:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0006_auto_20060828_0136'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='questioncomment',
            name='comment',
        ),
        migrations.AddField(
            model_name='commentcomment',
            name='comment_text',
            field=models.TextField(default='', max_length=400),
        ),
        migrations.AddField(
            model_name='questioncomment',
            name='comment_text',
            field=models.TextField(default='', max_length=400),
        ),
    ]
