# Generated by Django 3.0.2 on 2006-08-29 07:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Band',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stage_name', models.CharField(max_length=100, null=True)),
                ('date_formed', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Music',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('date_produced', models.DateField()),
                ('producer', models.CharField(max_length=100)),
                ('band', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bandcollections.Band')),
            ],
        ),
        migrations.CreateModel(
            name='Musician',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('real_name', models.CharField(max_length=100)),
                ('stage_name', models.CharField(max_length=100, null=True)),
                ('band', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='bandcollections.Band')),
            ],
        ),
        migrations.CreateModel(
            name='MusicTI',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('information', models.CharField(max_length=100)),
                ('music', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bandcollections.Music')),
            ],
        ),
        migrations.CreateModel(
            name='MusicianTI',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('information', models.CharField(max_length=100)),
                ('musician', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bandcollections.Musician')),
            ],
        ),
        migrations.CreateModel(
            name='MusicianDI',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('information', models.TextField(max_length=100)),
                ('musician', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bandcollections.Musician')),
            ],
        ),
        migrations.CreateModel(
            name='MusicDI',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('information', models.TextField(max_length=100)),
                ('music', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bandcollections.Music')),
            ],
        ),
        migrations.CreateModel(
            name='BandTI',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('information', models.CharField(max_length=100)),
                ('band', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bandcollections.Band')),
            ],
        ),
        migrations.CreateModel(
            name='BandDI',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('information', models.TextField(max_length=100)),
                ('band', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bandcollections.Band')),
            ],
        ),
    ]
