# Generated by Django 3.0.2 on 2006-08-30 21:05

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('bandcollections', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='band',
            name='date_formed',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
