# Generated by Django 3.0.2 on 2006-09-01 03:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bandcollections', '0002_auto_20060831_0005'),
    ]

    operations = [
        migrations.AlterField(
            model_name='band',
            name='stage_name',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='musician',
            name='real_name',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='musician',
            name='stage_name',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
